/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.scenario.testing;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.provider.Provider;

/**
 * A simple 'hello world' plugin.
 */
public class GradleScenarioTestingPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("theTask", TheTask.class, task -> {
            Provider<String> theText = project.getProviders().gradleProperty("theText")
                    .forUseAtConfigurationTime()
                    .orElse("Coucou");
            task.getTheText().set(theText);
            task.getTheFile().convention(project.getLayout().getBuildDirectory().file("the-file.txt"));
        });
    }
}
